### ISSUE TITLE
Run the program

### ISSUE THREAD

**Issue by WeiJenLee** [bryankim96/stux-DNN#3]
Hello,

I'm wondering how to run this program. For the code in MNIST, if I want to run the experiment with that dataset, should I first train a model?

**Comment by raphael-s-norwitz** [comment]
Yes, you need to train the model first. Navigate to the `/mnist` directory and run `python3 model.py`. After you have trained the model, run `python3 train_sparse_update.py`, which prints the results.

**Comment by WeiJenLee** [comment]
Thank you for answering. How about trojan.py?

**Comment by raphael-s-norwitz** [comment]
As said in the README, it re implements the work of https://docs.lib.purdue.edu/cstech/1781/

**Comment by raphael-s-norwitz** [comment]
Let me know if you have additional questions - closing for now
